# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='ianus',
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
