# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensoria',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
