# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_auto_20160101_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='cod_ianus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='opinion',
            field=models.NullBooleanField(default=False),
        ),
    ]
