# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_accion', models.DateField()),
                ('accion', models.CharField(max_length=100)),
                ('f_resultado', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('pag_adjuntas', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Defensoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_denuncia', models.DateField()),
                ('codigo_dna', models.CharField(max_length=10)),
                ('nro_atencion', models.CharField(max_length=10)),
                ('inhabilitado', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('opinion', models.BooleanField(max_length=255)),
                ('historia', models.TextField()),
                ('create', models.DateField(auto_now_add=True)),
                ('modificate', models.DateField(auto_now=True)),
                ('defensoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Defensoria')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('create', models.DateField(auto_now_add=True)),
                ('modificated', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True)),
                ('modificated', models.DateField(auto_now=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Denuncia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('f_creacion', models.DateField(auto_now_add=True)),
                ('f_modificacion', models.DateField(auto_now=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('gestante', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('f_nac', models.DateField(blank=True, null=True)),
                ('c_nac', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('estudia', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('ult_curso', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo_trabajo', models.CharField(blank=True, max_length=40, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=40, null=True)),
                ('g_instruccion', models.CharField(blank=True, max_length=40, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=40, null=True)),
                ('cedula', models.CharField(blank=True, max_length=40, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=40, null=True)),
                ('create', models.DateField(auto_now_add=True)),
                ('modificate', models.DateField(auto_now=True)),
                ('anonimo', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.ManyToManyField(to='denuncias.Tipo'),
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Persona'),
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Tipo'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Persona'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Tipologia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Denuncia'),
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
