# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logestado',
            name='activo',
            field=models.NullBooleanField(),
        ),
    ]
