# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_logestado_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal', models.CharField(max_length=100)),
                ('juzgado', models.CharField(max_length=100)),
                ('tar', models.CharField(max_length=30)),
                ('ianus', models.CharField(max_length=30)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Denuncia')),
            ],
        ),
    ]
