# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_juzgado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_notificacion', models.DateField()),
                ('notificacion', models.CharField(max_length=255)),
                ('vista', models.BooleanField()),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
