# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_notificaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
