# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_auto_20151230_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='completa',
            field=models.NullBooleanField(default=False),
        ),
    ]
