# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_denuncia_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='opinion',
            field=models.NullBooleanField(),
        ),
    ]
